### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xAffan** [WaxMoon/MultiApp#11]
8 ball pool crashes in this app

**Comment by WaxMoon** [comment]
You now can use old version! Download here (https://www.apkmirror.com/apk/miniclip-com/8-ball-pool/8-ball-pool-5-10-3-release/8-ball-pool-5-10-3-2-android-apk-download/download/?key=d9f782ebb02dbea5ef52da4ca2943099e76248f3&forcebaseapk=true).

I will try to fix！tks！

**Comment by WaxMoon** [comment]
Please try our official MultiApp1.1.10(https://play.google.com/store/apps/details?id=com.waxmoon.ma.gp). We have fixed! This issue will be closed tomorrow
