### ISSUE TITLE
如何免安装第三方App? 

### ISSUE THREAD

**Issue by spysoos** [WaxMoon/MultiApp#12]
Release里的Apk 如何免安装第三方App? 比如选择sd卡上的apk进行安装？能提供从sd卡安装apk的功能吗？

**Comment by WaxMoon** [comment]
Cmd.INSTANCE().exec(
                CmdConstants.CMD_INSTALL_PACKAGE,
                userId, apkFilePath,
                MODE_INSTALL_ALONE)

**Comment by spysoos** [comment]
![image](https://user-images.githubusercontent.com/982866/207768260-bc89b144-b386-4388-a555-ee7652189528.png)
安装本地apk 出现这个错误 是清单解析出问题吗？

**Comment by WaxMoon** [comment]
> ![image](https://user-images.githubusercontent.com/982866/207768260-bc89b144-b386-4388-a555-ee7652189528.png) 安装本地apk 出现这个错误 是清单解析出问题吗？

@NewbeMa confirm it

**Comment by WaxMoon** [comment]
@spysoos Update submodule-opensdk and retry
