### ISSUE TITLE
关于容器相关功能

### ISSUE THREAD

**Issue by jiangfeng0103** [WaxMoon/MultiApp#14]
1、是否可以自定义容器信息，mac，imei,手机型号，手机号，手机制造商.....等信息
2、是否可以提供获取已创建容器数量及信息。

**Comment by WaxMoon** [comment]
1.MultiApp默认已经针对空间级别设置了不同了deviceId、wifiMac、btMac等信息。当然您也可以自己写hook代码做二次开发自定义容器信息
2.参考HackApi.getAvailableUserSpace/getInstalledPackages

@jiangfeng0103
