### ISSUE TITLE
F-Droid support

### ISSUE THREAD

**Issue by tvnmguy** [WaxMoon/MultiApp#16]
Make this amazing app available in f-droid official repository.

Thank you!

**Comment by danielphan2003** [comment]
> Make this amazing app available in f-droid official repository.
> 
> Thank you!

It is available on IzzyOnDroid repo in the mean time. You can add it to your f-droid client while waiting for official f-droid release.

**Comment by WaxMoon** [comment]
Tks for your answer @danielphan2003!

**Comment by parcelcat** [comment]
@WaxMoon While Multi App is in the IzzyOnDroid repository, it's not in the official F-Droid repository yet. Would you consider [submitting the app to F-Droid](https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/)?

Being in the official F-Droid repository shows that the source code has been reviewed by the F-Droid maintainers, which carries a level of trust. F-Droid also supports [reproducible builds](https://f-droid.org/en/docs/Reproducible_Builds/) as an option.

**Comment by linsui** [comment]
I can help package it for F-Droid. When I checked your apk, I found that there is another apk embeded in it. I didn't find how to build the embeded apk and it seems it's not FOSS. I can't find what it's for, either. Therefore, I can't build your apk reproducibly. I also [reported](https://gitlab.com/IzzyOnDroid/repo/-/issues/345) this problem to @Izzysoft .

**Comment by IzzySoft** [comment]
@WaxMoon ^^ Maybe that APK (or rather "the APKs", there are 2 inside) does not even belong there and slipped in accidentally? One of them contains 2 proprietary libraries and seems to be intended for Playstore listing.
