### ISSUE TITLE
Install apk

### ISSUE THREAD

**Issue by NSTAdventure** [WaxMoon/MultiApp#17]
Please add support to install apk / apks and such package installer too instead from clone installed apps thanks 🙏😄

**Comment by WaxMoon** [comment]
git pull and Update your code. You can see HackApi.installApkFiles
https://github.com/WaxMoon/opensdk/commit/fb47d9560bebf4bc340b1c262bd599432524abe0

**Comment by NSTAdventure** [comment]
> git pull and Update your code. You can see HackApi.installApkFiles [WaxMoon/opensdk@fb47d95](https://github.com/WaxMoon/opensdk/commit/fb47d9560bebf4bc340b1c262bd599432524abe0)
I not understand anything related to code sir 
That's why i only able to share my idea

My apologies for this inconvenience 🙏😞

**Comment by WaxMoon** [comment]
Reopen! I will refact the code and support to install apk directly

**Comment by spysoos** [comment]
@WaxMoon 
`MoonApplication.INSTANCE().packageManager.getLaunchIntentForPackage(info.packageName) return null ` return null , how can i start the App which install from sdcard?

**Comment by WaxMoon** [comment]
HackApi.getLaunchIntentForPackage and HackApi.startActivity
