### ISSUE TITLE
sad bug

### ISSUE THREAD

**Issue by Wjxfi** [WaxMoon/MultiApp#21]
When I enter the app, I see this and nothing else
![300009.jpg](https://user-images.githubusercontent.com/113500363/211906165-455e8db0-afcc-4cbf-a31b-96eaa315c71c.jpg)

miui 12.0.5 
android 12
1.0.6 ver.

**Comment by WaxMoon** [comment]
Can you join whatsapp group(https://github.com/WaxMoon/MultiApp)?  or Wechat(WaxMoon2018)?
I need more info. Tks

**Comment by WaxMoon** [comment]
Please provide app logs. Tks! 
If there are some troubles, You can view https://developer.android.google.cn/studio/command-line/logcat.

**Comment by WaxMoon** [comment]
Plz download apk from https://play.google.com/store/apps/details?id=com.waxmoon.ma.gp
