### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Werewolfke** [WaxMoon/MultiApp#24]
idk where to ask, so i'll ask here.
Maybe the option to have serten apps pinned to the top for every space.
Would be helpfull instead of having to scroll trough a list of over 600 apps for that 1 app i use it for.

and if its possible even pin it to the homescreen, but that is really extra if its possible.

otherwise Lovely app <3

**Comment by WaxMoon** [comment]
@Werewolfke You can download official app from Google Play
https://play.google.com/store/apps/details?id=com.waxmoon.ma.gp
