### ISSUE TITLE
Shared Folder data

### ISSUE THREAD

**Issue by erixjunior** [WaxMoon/MultiApp#33]
Hello mr, i have some question, 
Why i can't find targeted folder for data app in the source code, i want to edit the specific target ext 'rootf/emulated/0" and "rootf/emulated/1" into "rootf/emulated/shared" for cloned app data and i don't want it splited because some games have a large data capacity and do not allow for many clones in a limited space, please help

**Comment by WaxMoon** [comment]
rootfs/storage/emulated/0

**Comment by erixjunior** [comment]
Yes but how to change the destination?
