### ISSUE TITLE
versionCode not increased

### ISSUE THREAD

**Issue by IzzySoft** [WaxMoon/MultiApp#8]
Looks like all your releases have the same `versionCode: 1`. As this is what Android uses internally to tell versions apart: could you please take care to [always increase it](https://github.com/WaxMoon/MultiApp/blob/main/build.gradle#L34) before tagging & building a new release? Thanks in advance!

**Comment by WaxMoon** [comment]
v1.0.3 fix! tks! @IzzySoft

**Comment by IzzySoft** [comment]
Confirmed – thanks!

**Comment by IzzySoft** [comment]
PS: If you want to add an alternative way to install your app and keep up with updates, [see here](https://apt.izzysoft.de/fdroid/index/apk/org.waxmoon.github32). New APKs are fetched within 24h of your tagging and attaching them. Currently I take the armeabi variant (for widest compatibility); I will probably switch to preferring arm64 one day, but no ETA for that yet (certainly not before 2024).
