### ISSUE TITLE
Release a single apk combining both 32 and 64 bit versions

### ISSUE THREAD

**Issue by TechMorgan** [WaxMoon/MultiApp#9]

**Comment by WaxMoon** [comment]
Wait patiently for a week! I will do it! @TechMorgan

**Comment by NSTAdventure** [comment]
> Wait patiently for a week! @xunijun will do it! @TechMorgan

Honestly i also waiting for this i hope dev consider it thanks 🙏😊

**Comment by WaxMoon** [comment]
try v1.0.4 @NSTAdventure

**Comment by IzzySoft** [comment]
Ouch. That just broke [your listing with my repo](https://apt.izzysoft.de/fdroid/index/apk/org.waxmoon.github32) as the armeabi build went missing and file names changed, so I had to disable updates for now. Can you please add the 32bit variant back, @WaxMoon? The one which is attached to the last release carries the name of the 64bit build. It would also be very helpful if the file names kept consistent (so my updater has a chance to pick the right one; up to now it told them apart by "App64" vs "App32").

As you used different package names for them, you cannot simply combine them to a single APK without forcing half the users to uninstall and reinstall, unfortunately.
